volumes:
  'postgres_data': {}
  'redis_data': {}

services:
  postgresql:
    image: 'postgres:15'
    container_name: 'knowledge_admin_postgres'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    env_file:
      - ./env/public
      - ./env/secret
    ports:
      - '5432:5432'

  redis:
    image: redis:6
    container_name: 'knowledge_admin_redis'
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - 'redis_data:/data'
    env_file:
      - ./env/public
      - ./env/secret
    ports:
      - '6379:6379'
