include:
  - ./compose.db.yaml

services:
  ui: &django
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    image: 'knowledge_admin_django'
    container_name: 'knowledge_admin_ui'
    depends_on:
      - postgresql
      - redis
    volumes:
      - '.:/app:z'
    env_file:
      - ./env/public
      - ./env/secret
    ports:
      - '8000:8000'
    command: /start-ui

  api:
    <<: *django
    container_name: 'knowledge_admin_api'
    depends_on:
      - postgresql
      - redis
    ports:
      - '8080:8000'
    command: /start-api

  worker:
    <<: *django
    container_name: 'knowledge_admin_worker'
    depends_on:
      - redis
      - postgresql
    ports: []
    command: /start-worker

  scheduler:
    <<: *django
    container_name: 'knowledge_admin_scheduler'
    depends_on:
      - redis
      - postgresql
    ports: []
    command: /start-scheduler

  flower:
    <<: *django
    container_name: 'knowledge_admin_flower'
    ports:
      - '5555:5555'
    command: /start-flower
