volumes:
  'publisher_postgres_data': {}
  'publisher_postgres_data_backups': {}
  'publisher_redis_data': {}

services:
  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: 'publisher_node'
    container_name: 'publisher_node'
    depends_on:
      - ui
    volumes:
      - '.:/app:z'
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'

  ui: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: 'publisher_ui'
    container_name: 'publisher_ui'
    depends_on:
      - postgres
      - redis
    volumes:
      - '.:/app:z'
    env_file:
      - ./.env/.django
      - ./.env/.postgres
      - ./.env/.redis
      - ./.env/.secret
    ports:
      - '8000:8000'
    command: /start-ui

  api:
    <<: *django
    image: 'publisher_api'
    container_name: 'publisher_api'
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8000'
    command: /start-api

  worker:
    <<: *django
    image: 'publisher_worker'
    container_name: 'publisher_worker'
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-worker

  scheduler:
    <<: *django
    image: 'publisher_scheduler'
    container_name: 'publisher_scheduler'
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-scheduler

  flower:
    <<: *django
    image: 'publisher_flower'
    container_name: 'publisher_flower'
    ports:
      - '5555:5555'
    command: /start-flower

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: 'publisher_postgres'
    container_name: 'publisher_postgres'
    volumes:
      - 'publisher_postgres_data:/var/lib/postgresql/data'
      - 'publisher_postgres_data_backups:/backups'
      - ./restore:/restore
    env_file:
      - ./.env/.postgres
      - ./.env/.secret
    ports:
      - '5432:5432'

  redis:
    image: redis:6
    container_name: 'publisher_redis'
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - 'publisher_redis_data:/data'
    env_file:
      - ./.env/.redis
      - ./.env/.secret
    ports:
      - '6379:6379'
