# Generated by Django 5.1.4 on 2025-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0007_alter_textembedding_options_alter_textembedding_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formsubmission",
            name="nav_path",
        ),
        migrations.RemoveField(
            model_name="formsubmission",
            name="page",
        ),
        migrations.RemoveField(
            model_name="formsubmission",
            name="session_id",
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="email",
            field=models.CharField(default="nobody@example.com", max_length=50, verbose_name="User Email"),
            preserve_default=False,
        ),
    ]
