# Generated by Django 5.1.4 on 2025-04-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0008_remove_formsubmission_nav_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="type",
            field=models.CharField(default="submission", max_length=50, verbose_name="Type"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="email",
            field=models.CharField(max_length=512, verbose_name="User Email"),
        ),
    ]
